apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-yaml
    method: fromCode
    label2: anotherLabel
    label3: anotherLabel2
  name: nginx-yaml
spec:
  containers:
  - image: nginx
    name: nginx-yaml
